config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  get "up" => "rails/health#show", as: :rails_health_check

  # get "bookmarks", to: "bookmarks#index"
  # get "bookmarks/lists", to: "bookmarks#create", as: :lists
  # get "bookmarks/movies", to: "bookmarks#create", as: :movies

  # Defines the root path route ("/")
  root "lists#index"

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movies
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is alreadyin the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

# https://stackoverflow.com/questions/17380794/how-to-forbid-deletion-if-association-present

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id]) # define the list
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(:list_id) # define the list
    @bookmark = Bookmark.new(bookmark_params) # create a new bookmark with params
    @bookmark.list = @list # attach the lidt to the bookmark
      if @bookmark.save # if save, redirect to the show
        redirect_to list_path(@list)
      else
        redirect_to list_path(@list), status: :unprocessable_entity #redirect to list show
        # render :new, status: unprocessable_entity # if not save, render new (uncomment for rake test)
      end
  end

  def destroy
    @bookmark = Bookmar.find(params[:id]) # get the bookmark
    @bookmark.destroy # destroy the bookmark
    redirect_to list_path(@bookmark.list), status: :see_other #redirect to the bookmark's list
  end

  private
  def bookmark_params # string params
    params.require(:bookmark).permit(:move_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    # get all the lists
    @lists = List.all
    @list = List.new # define new list for form rendered on the List index
  end

  def show
    # get a list
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      @list = List.all
        # render :new, status: :unprocessable_entity # reroute to new (uncomment for rspec)
        render :index, status: :unprocessable_entity # route to index
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/create.html.erb
<div class="flex-container">
  <h1>hBookmarks#create</h1>
  <p>Find me in app/views/bookmarks/create.html.erb</p>
    <div class="flex-item">...</div>
    <div class="flex-item">...</div>
    <div class="flex-item">...</div>
</div>

app/views/bookmarks/new.html.erb
<h1>hBookmarks#create</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="flex-container row justify-content-center">
  <h1 class="text-center">My Movie List</h1>
  <div class="col-9">
    <ul>
      <% @lists.each do |list|%>
        <li> <%= link_to list.name, list_path(list) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="flex-container container row justify-content-center">
  <%= simple_form_for @list do |f|%>
    <%= f.input :name %>
    <%= f.submit "Add a List", class: "btn btn-warning" %>
  <% end %>
</div>

  <% if @list.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h4>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/lists/show.html.erb
<h1 class="text-center">List Details</h1>
<div class="container mt-3">
  <div class="row">
    <div class="col-8">
      <div class="cards">
        <%= @list.bookmarks.each do |bookmark| %>
          <div class="card-trip">
            <%= image_tag bookmark.movie.poster_url %>
            <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
            <div class="card-trip-infos">
              <div>
                <h2><%= bookmark.movie.title %>
                <p><%= bookmark.movie.overview %></p>
                <h2 class="card-trip-pricing"><%= bookmark.comment %></h2>
              </div>
            </div>
          </div>
        <% end %>
      </div>

<div class="form-control">
  <%= simple_form_for ([@list, @bookmark || Bookmark.new]) do |f| %>
    <%= f.inout :comment %>
    <%= f.association :movie, placeholder: "Select a Movie" %>
    <%= f.button :submit %>
  <% end %>
</div>